import test from "node:test";
import assert from "node:assert/strict";
import {venueChecks} from "./probes.mjs";
const now=Date.parse("2026-09-17T12:00:00Z");
const sample=(overrides={})=>({venue:"lighter",scenario:"single",order_type:"post_only",plot_at:new Date(now-30000).toISOString(),ok:true,...overrides});
test("detects missing Lighter while other venues continue",()=>{const checks=venueChecks([sample({venue:"aster"})],now);assert.equal(checks.find(v=>v.name==="lighter").status,"issue");assert.equal(checks.find(v=>v.name==="aster").status,"ok")});
test("detects stale successful data even with recent failures",()=>{const v=venueChecks([sample({plot_at:new Date(now-6*60000).toISOString()}),sample({ok:false})],now)[0];assert.equal(v.status,"issue");assert.equal(v.age,360)});
test("rejects malformed payload instead of reporting passing",()=>{assert.throws(()=>venueChecks(null,now));assert.throws(()=>venueChecks([{venue:"lighter",plot_at:"broken",ok:true}],now))});
test("error ratio uses minimum sample count",()=>{assert.equal(venueChecks([sample(),sample({ok:false})],now)[0].status,"ok");assert.equal(venueChecks([sample(),sample(),sample(),sample({ok:false}),sample({ok:false})],now)[0].status,"issue")});
test("batch samples do not hide missing single-order data",()=>assert.equal(venueChecks([sample({scenario:"batch"})],now)[0].status,"issue"));
