"use client";
import {useEffect,useState,useRef} from "react";
import {Activity,ArrowUpRight,Bell,RefreshCw,ShieldCheck,Radio,TriangleAlert} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
const names:Record<string,string>={lighter:"Lighter",hyperliquid:"Hyperliquid",extended:"Extended",nado:"Nado",aster:"Aster"};
const time=(s:string)=>new Date(s).toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
export default function Home(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[tab,setTab]=useState("Overview"),[filter,setFilter]=useState("All"),[message,setMessage]=useState("");
 const api=useRef<string|null>(null),fetching=useRef(false);
 async function backend(){if(api.current!==null)return api.current;const r=await fetch('./runtime-config.json',{cache:'no-store'});if(!r.ok)throw Error('Unable to load dashboard configuration');const c=await r.json();api.current=c.backendUrl??'';return api.current}
 async function load(run=false){
  if(fetching.current)return;fetching.current=true;setBusy(true);setError('');setMessage('');
  try{
   const base=await backend();
   if(run&&base){const r=await fetch(base+'/check',{method:'POST'});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to start check');if(result.cooldown)setMessage('A check just finished. Showing the latest results; another check is available in '+result.cooldown+' seconds.')}
   const deadline=Date.now()+240000;
   while(true){const r=await fetch(base?base+'/dashboard':'./data/dashboard.json?t='+Date.now(),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load results');setData(d);
    if(!run||!base||!d.monitor?.running){if(d.monitor?.lastError)setError('The last check failed. Results may be stale.');break}
    if(Date.now()>deadline)throw Error('The check is taking longer than expected. Results will update automatically.');await new Promise(resolve=>setTimeout(resolve,2000));
   }
  }catch(e){setError((e as Error).message)}finally{fetching.current=false;setBusy(false)}
 }
 useEffect(()=>{load();const t=setInterval(()=>load(),15000);return()=>clearInterval(t)},[]);
 const checks=data?.snapshot?.checks??[],open=data?.incidents.filter((i:any)=>!i.resolved_at)??[],issues=checks.filter((c:any)=>c.status==="issue");
 const stale=data?.snapshot&&Date.now()-Date.parse(data.snapshot.checkedAt)>(data?.monitor?.hosted?180000:900000);
 const incidents=(data?.incidents??[]).filter((i:any)=>filter==="All"||(filter==="Open"?!i.resolved_at:!!i.resolved_at));
 return <div className="shell"><aside className="sidebar"><a className="brand" href="./"><span className="brand-icon"><Activity size={23}/></span>Baby Watchtower</a><nav>{["Overview","Incidents","Checks","Alerts"].map((t,i)=><Button variant="ghost" className={tab===t?"nav-item selected":"nav-item"} key={t} aria-current={tab===t?"page":undefined} onClick={()=>setTab(t)}>{i===0?<Activity/>:i===1?<TriangleAlert/>:i===2?<ShieldCheck/>:<Bell/>}{t}{t==="Incidents"&&open.length>0&&<span className="nav-count">{open.length}</span>}</Button>)}</nav></aside>
 <main><header><h1>{tab}</h1><Button onClick={()=>load(true)} disabled={busy} className="run-button"><RefreshCw className={busy?"spin":""}/>{busy?(api.current?"Checking…":"Refreshing…"):"Refresh"}</Button></header><div className="content">
 {message&&<div role="status" className="monitor-note">{message}</div>}
 {error&&<div role="alert" className="error-banner">{error}<Button variant="outline" onClick={()=>load()}>Retry</Button></div>}
 <div className="monitor-note"><Radio size={17}/><span>{data?.monitor?.hosted?'Checks run every minute. Refresh starts a check; requests within 60 seconds share the latest result.':'Background checks scheduled every 5 minutes. Runs may be delayed; results refresh automatically.'}</span></div>
 {stale&&<div className="error-banner" role="status">Monitoring results are over {data?.monitor?.hosted?'3':'15'} minutes old. The background checker may be delayed or stopped.</div>}
 {tab==="Overview"&&<><section className="summary"><div><span>Current health</span><strong className={issues.length?"amber":""}>{!data?.snapshot?"Not checked":stale?"Results stale":issues.length?"Needs attention":"Checks passing"}</strong><small>Configured checks only</small></div><div><span>Websites</span><strong>02</strong><small>Litscan + Perps Latency</small></div><div><span>Open incidents</span><strong>{data?String(open.length).padStart(2,"0"):"—"}</strong><small>Two failures to confirm</small></div><div><span>Last checked</span><strong className="time-value">{data?.snapshot?new Date(data.snapshot.checkedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</strong><small>{data?.snapshot?time(data.snapshot.checkedAt):"Waiting for the first scheduled check"}</small></div></section>
 <div className="section-heading"><h2>Websites</h2></div><section className="site-grid">{[{id:"litscan",name:"Litscan",url:"https://litscan.io",desc:"Lighter explorer & analytics",letter:"L"},{id:"latency",name:"Perps Latency",url:"https://latency.perps.trading",desc:"Exchange latency benchmarks",letter:"↗"}].map(s=>{const cs=checks.filter((c:any)=>c.site===s.id),bad=cs.filter((c:any)=>c.status==="issue");return <article className="site-card" key={s.id}><div className="site-card-top"><div className={"site-icon "+s.id}>{s.letter}</div><div><h3>{s.name}</h3><a href={s.url} target="_blank" rel="noreferrer">{s.url.replace("https://","")} <ArrowUpRight size={13}/></a></div><Badge className={"status "+(bad.length?"issue":cs.length?"ok":"unknown")}>{bad.length?"Attention":cs.length?"Passing":"Not checked"}</Badge></div><div className="check-list">{cs.length?cs.slice(0,4).map((c:any)=><div key={c.id}><span className={"dot "+c.status}/><span>{c.name}</span><b className={c.status==="issue"?"amber":""}>{c.status==="issue"?"Review":c.status==="unknown"?"Unverified":c.ms!==undefined?c.ms+" ms":"Passing"}</b></div>):<div className="empty-inline">Waiting for results.</div>}</div><div className="site-footer"><span>{s.id==="litscan"?"Page checks only · data not verified":cs.length+" configured checks"}</span><Button variant="ghost" onClick={()=>setTab("Checks")}>View checks <ArrowUpRight/></Button></div></article>})}</section>
 <section className="panel"><div className="section-heading"><h2>Venue freshness</h2><span>Sample age at last check · 5 minute threshold</span></div><div className="venue-grid">{Object.keys(names).map(id=>{const v=data?.snapshot?.venues.find((x:any)=>x.name===id);return <div className="venue" key={id}><span className={"dot "+(v?.status??"unknown")}/><strong>{names[id]}</strong><span className={v?.status==="issue"?"amber":""}>{!v?"Not checked":v.age===null?"Missing":Math.floor(v.age/60)+"m "+Math.floor(v.age%60)+"s ago"}</span><small>{v?v.count+" samples · "+v.failed+" failed":"Awaiting first observation"}</small></div>})}</div></section></>}
 {(tab==="Overview"||tab==="Incidents")&&<section className="panel"><div className="section-heading"><h2>Incident history</h2><div className="filters">{["All","Open","Resolved"].map(f=><Button size="sm" variant={f===filter?"secondary":"ghost"} onClick={()=>setFilter(f)} key={f}>{f}</Button>)}</div></div>{!incidents.length?<div className="empty-state"><ShieldCheck/><h3>{data?.snapshot?"No matching incidents":"No checks yet"}</h3><p>Two failed runs open an incident. Two passing runs resolve it.</p></div>:incidents.slice(0,tab==="Overview"?6:100).map((i:any)=><details className="incident" key={i.id}><summary><span className={"dot "+(i.resolved_at?"ok":"issue")}/><div><strong>{i.name}</strong><small>{i.site==="litscan"?"Litscan":"Perps Latency"} · {time(i.opened_at)}</small></div><Badge className={"status "+(i.resolved_at?"ok":"issue")}>{i.resolved_at?"Resolved":"Open"}</Badge></summary><p>{i.detail}</p>{i.resolved_at&&<p>Recovered {time(i.resolved_at)}</p>}</details>)}</section>}
 {tab==="Checks"&&<><section className="panel"><div className="section-heading"><h2>Checks</h2><span>{checks.length} observations</span></div>{checks.length?checks.map((c:any)=><div className="coverage-row" key={c.id}><span className={"dot "+c.status}/><div><h3>{c.name}</h3><p>{c.detail}</p><a href={c.url} target="_blank" rel="noreferrer">Inspect source <ArrowUpRight size={13}/></a></div><Badge className={"status "+c.status}>{c.status==="ok"?"Passing":c.status==="issue"?"Review":"Unverified"}</Badge></div>):<div className="empty-state">Waiting for results.</div>}</section><section className="panel coverage-notes"><h2>What is checked</h2><p>Checks cover HTTP errors and timeouts, expected page titles and JavaScript assets, benchmark health, JSON structure, feed freshness, venue presence, successful sample freshness and recent measurement errors.</p><p>Litscan’s application data, rendered charts, login flows, WebSocket delivery, certificate expiry, internal logs and multi-region availability need additional probes. A passing page check does not verify its charts.</p><p>Slow responses over 5 seconds are flagged. Successful venue samples must be newer than 5 minutes. Failure rates above 20% require at least 5 recent samples.</p></section></>}
 {tab==="Alerts"&&<section className="panel alert-settings"><h2>Email</h2><Badge className={"status "+(data?.email?.configured?"ok":"unknown")}>{data?.email?.configured?"Credentials configured":"Sender setup needed"}</Badge><p>Incident and recovery emails go to the recipient saved privately in GitHub.</p>{data?.email?.deliveryError&&<p className="amber">Email delivery failed. The next check will retry.</p>}{data?.email?.pending>0&&<p>{data.email.pending} notifications queued.</p>}<p>Owner setup: add GMAIL_USER and GMAIL_APP_PASSWORD to <a href="https://github.com/Yingzi-Qi/baby-watchtower/settings/secrets/actions" target="_blank" rel="noreferrer">GitHub secrets ↗</a>. Use a Google App Password, not your normal password. The first configured check sends a setup confirmation email.</p><hr/><h2>Telegram</h2><Badge className={"status "+(data?.telegram?"ok":"unknown")}>{data?.telegram?"Credentials configured":"Setup needed"}</Badge>{data?.telegram&&data.pendingAlerts>0&&<p className="amber">{data.pendingAlerts} notifications queued.</p>}{data?.deliveryError&&<p className="amber">Telegram delivery failed. The next check will retry.</p>}<p>One bot, any device. The recipient opens a private pairing link in Telegram and taps Start.</p><ol><li>The owner creates a bot with <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a> using <code>/newbot</code>.</li><li>On the owner’s computer, run <code>python3 scripts/setup_telegram.py</code> from the repository. Python 3 and GitHub CLI signed in with repository access are required.</li><li>Paste the token into the hidden prompt, then send the generated pairing link to the recipient. After they tap Start, pairing saves the settings and sends a confirmation.</li></ol><p className="muted">The recipient needs only Telegram. Keep the bot token and pairing link private. Pairing replaces the configured Telegram recipient.</p><a href="https://github.com/Yingzi-Qi/baby-watchtower#telegram" target="_blank" rel="noreferrer">Setup instructions ↗</a><hr/><h3>Monitoring</h3><p>{data?.monitor?.hosted?'Checks run on the hosted service every minute, even with your browser closed.':'Checks run on GitHub about every five minutes; scheduled runs may be delayed.'} Incidents and recoveries require two consecutive observations.</p><a href="https://github.com/Yingzi-Qi/baby-watchtower/actions" target="_blank" rel="noreferrer">View monitoring runs ↗</a></section>}
 </div></main></div>
}
